<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('assets/doctrine-gui/css/style.css'))
                        ->prependStylesheet($this->basePath('assets/doctrine-gui/css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('assets/doctrine-gui/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('assets/doctrine-gui/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/doctrine-gui/js/jquery.min.js'))
            ->prependFile($this->basePath('assets/doctrine-gui/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('assets/doctrine-gui/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); ?>

        <?php
        $sidebarPage = $_SERVER['REQUEST_URI'];
        if (substr($sidebarPage,0,1) == '/') {
            $sidebarPage = substr($sidebarPage,1);
        }
        $parts  = explode('/',$sidebarPage);
        $parent = strtolower(isset($parts[0]) ? $parts[0] : '');
        $child  = strtolower(isset($parts[1]) ? $parts[1] : '');

        $active['overview'] = '';
        $active['clients']  = '';
        $active['scopes']   = '';

        if ( $child === 'overview')
        {
            $active['overview'] = 'active';
        }

        if ( $child === 'clients')
        {
            $active['clients'] = 'active';
        }

        if ( $child === 'scopes')
        {
            $active['scopes'] = 'active';
        }

        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('assets/doctrine-gui/img/zf2-logo.png') ?>" alt="ZF Oauth2 Doctrine Gui"/>&nbsp;<?php echo $this->translate('OAuth2 Doctrine Gui') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<?=$active['overview']?>"><a href="<?php echo $this->url('zf-oauth-doctrine-gui/overview') ?>"><?php echo $this->translate('Overview') ?></a></li>
                        <li class="<?=$active['clients']?>"><a href="<?php echo $this->url('zf-oauth-doctrine-gui/clients') ?>"><?php echo $this->translate('Clients') ?></a></li>
                        <li class="<?=$active['scopes']?>"><a href="<?php echo $this->url('zf-oauth-doctrine-gui/scopes') ?>"><?php echo $this->translate('Scopes') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Author: <a href="http://www.southeasterdesign.com" target="_blank">www.southeasterdesign.com</a> find on GitHub: <a href="https://github.com/API-Skeletons/zf-oauth2-doctrine-gui">Zf OAuth Doctrine Gui</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
