<?php
$this->layout('doctrine-gui/layout');
?>
<?php
$this->FlashMessengerHelper();
?>
<div>
    <div class="row profile-account">
        <div class="col-md-12">
            <div class="tab-content">
                <div>
                    <p>
                        Create clients for:</p>
                    <ul>
                        <li>SSO access (Grant: implicit, Scope: basic)</li>
                        <li>Secure server to server communication (Grant: urn:ietf:params:oauth:grant-type:jwt-bearer, Scope: basic, add your secure keys)</li>
                    </ul>


                    <p>Scopes</p>
                   <p>You are free to create additional scopes to suit your needs. Take a look at our cookbook to see how these can be used in your API.</p>

                    <p>
                        <b>Naming convention:</b> Make sure you name your clients in an easy to remember manner: e.g.: application_name_test_client
                    </p>
                    <p>
                        <a class="btn btn-primary btn-lg" href="<?=$this->url('zf-oauth-doctrine-gui/client-manage');?>">
                            <i class="fa fa-cloud"></i> New client</a>
                    </p>
                    <div class="col-md-12">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Details</th>
                                <th>Public key</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                                foreach ($client_array AS $client ) {
                            ?>
                            <tr>
                                <td>
                                    <b>Client id (name):</b> <?=$client['array_copy']['clientId'];?><br/>
                                    <b>Client user identity:</b>

                                    <?php
                                        $userObject = $client['array_copy']['user'];

                                        if ($userObject instanceof \ZF\OAuth2\Doctrine\Entity\UserInterface)
                                        {
                                            echo $userObject->getId();
                                        }
                                    ?><br/>

                                    <b>JWT subject (user id):</b> <?= (isset($client['public_key']['subject'])) ? $client['public_key']['subject'] : 'Add public key to set';?><br/>
                                    <b>Return uri:</b> <?=($client['array_copy']['redirectUri'] == '') ? 'This must be set for security purposes' : $client['array_copy']['redirectUri'];?><br/>
                                    <b>Grant:</b> <?=implode(', ',$client['array_copy']['grantType']);?><br/>
                                    <b>Scope:</b> <?=implode(', ',$client['scope']);?><br/><br/>
                                    <p>
                                        <a class="btn btn-primary btn-xs" href="<?=$this->url('zf-oauth-doctrine-gui/client-manage', ['client_id' => $client['array_copy']['id']]);?>">
                                            <i class="fa fa-cloud"></i> Edit Client</a>

                                        <?php if (in_array('urn:ietf:params:oauth:grant-type:jwt-bearer',$client['array_copy']['grantType'])) { ?>
                                            <a class="btn btn-primary btn-xs" href="<?= $this->url('zf-oauth-doctrine-gui/manage-key',['client_id' => $client['array_copy']['id'], 'jwt_id' => 0]); ?>">
                                                <i class="fa fa-key"></i> Add Public Key</a>
                                        <?php } ?>

                                        <a class="btn btn-primary btn-xs" href="<?=$this->url('zf-oauth-doctrine-gui/delete-client', ['client_id' => $client['array_copy']['id']]);?>">
                                            <i class="fa fa-key"></i> Delete Client</a><br/><br/>

                                        <?php if ( in_array('implicit',$client['array_copy']['grantType']) ) {?>
                                        <a class="btn btn-primary btn-xs" target="_blank" href="/oauth/authorize?client_id=<?=$client['array_copy']['clientId'];?>&response_type=token&state=your_random_token&redirect_uri=<?=$client['array_copy']['redirectUri'];?>">
                                            <i class="fa fa-cloud-download"></i> Test SSO Login</a>
                                        <?php } ?>

                                        <?php if ( in_array('authorization_code',$client['array_copy']['grantType']) ) {?>
                                            <a class="btn btn-primary btn-xs" target="_blank" href="/oauth/authorize?client_id=<?=$client['array_copy']['clientId'];?>&response_type=code&state=your_random_token&redirect_uri=<?=$client['array_copy']['redirectUri'];?>">
                                                <i class="fa fa-cloud-download"></i> Test SSO Login</a>
                                        <?php } ?>

                                        <?php if ( in_array('urn:ietf:params:oauth:grant-type:jwt-bearer',$client['array_copy']['grantType']) AND !empty($client['public_key']) ) { ?>
                                            <a class="btn btn-primary btn-xs" href="<?=$this->url('zf-oauth-doctrine-gui/test-jwt' , [ 'jwt_id' => $client['public_key']['id'] , 'client_id' => $client['array_copy']['id'] ]);?>">
                                                <i class="fa fa-cloud-upload"></i> Test JWT Authentication</a>
                                        <?php }  ?>

                                    </p>
                                </td>
                                <td>
                                    <?php
                                        if ( is_array($client['public_key']) AND ! empty($client['public_key'])  )
                                        {
                                    ?>
                                    <textarea cols="60" rows="3" disabled><?=$client['public_key']['key'];?></textarea><br/>
                                            <a class="btn btn-primary btn-xs green" href="<?=$this->url('zf-oauth-doctrine-gui/manage-key', ['jwt_id' => $client['public_key']['id']]);?>">
                                                <i class="fa fa-key"></i> Edit Public Key</a>
                                            <a class="btn btn-primary btn-xs red" href="<?=$this->url('zf-oauth-doctrine-gui/delete-jwt-key', ['jwt_id' => $client['public_key']['id']]);?>">
                                                <i class="fa fa-key"></i> Delete Key</a><br/><br/>

                                    <?php } ?>
                                </td>
                            </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>
        </div>

    </div>
</div>