<?php
$this->layout('doctrine-gui/layout');
?>
<?php
$this->layout('doctrine-gui/layout');
?>
<?php
$this->FlashMessengerHelper();
?>

<div>
    <div class="row profile-account">
        <div class="col-md-12">
            <div class="tab-content">
                <div>
                    <p>
                        Use the OAuth2 Doctrine Gui to create clients for your API!
                    </p>
                    <p>
                        When selecting grant types:
                    </p>
                    <ul>
                        <li>Implicit: use for javascript or client side based apps</li>
                        <li>Authorization code: when you want the code to be received by the server</li>
                    </ul>
                    <p>The following is a good resource to get to know OAuth2 better:</p>
                    <ul>
                        <li><a href="http://tutorials.jenkov.com/oauth2/overview.html" target="_blank">Jakob Jenkov</a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>